language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.0.gemfile
  - gemfiles/rails-master.gemfile
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/rails-3.2.gemfile
