language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.0.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails-4.0.gemfile
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails-4.0.gemfile
